name: BCP_nosam
channels:
  - conda-forge
  - bioconda
  - defaults
  - r
dependencies:
  - python=3.11
  - scanpy=1.9.8    
  - pandas=2.2.2     
  - seaborn=0.13.2    
  - matplotlib=3.8.4  
  - multiqc=1.30      
  - star=2.7.10b
  - numpy=1.26.4
  - anndata=0.11.4

  - r-base=4.4
  - r-argparse
  - r-seurat=4.4.0
  - r-soupx=1.6.2
  - bioconductor-dropletutils=1.26.0
  - bioconductor-zellkonverter=1.16.0
  - bioconductor-singlecellexperiment=1.28.0
